# -*- coding: utf-8 -*-
"""Manav_Gupta_Tender V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ti1hbfBF3Kst4WP4GET3B20Gvdgmhwl3
"""

import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.expand_frame_repr', False)  # Prevent line wrapping
pd.set_option('display.width', 1000)  # Set display width to a large value

df = pd.read_csv("TenderData_v2.csv")

df.shape

df











df.description_eng.value_counts().reset_index()

df[df["description_eng"]=="Information technology and telecommunications consultants"]

filtered_df = df[(df["description_eng"].str.contains("server", case=False, na=False)) & (df["country_of_vendor_en"]=="Canada")]

filtered_df.owner_org_en.value_counts().reset_index()

filtered_df.description_eng.iloc[0]

def process_tenders(df, keyword):
    """
    Processes a DataFrame with tender data by:
    1. Subtracting start date from end date to calculate tender_days.
    2. Converting tender_days to tender_weeks.
    3. Filtering the dataset based on the keyword in the 'description_eng' column.

    Parameters:
    df (pd.DataFrame): The input DataFrame containing 'start_date', 'end_date', and 'description_eng'.
    keyword (str): The keyword to filter 'description_eng'.

    Returns:
    pd.DataFrame: A filtered DataFrame with additional columns 'tender_days' and 'tender_weeks'.
    """

    # Ensure date columns are in datetime format
    df["contract_period_start"] = pd.to_datetime(df["contract_period_start"], errors='coerce')
    df["delivery_date"] = pd.to_datetime(df["delivery_date"], errors='coerce')

    # Calculate tender_days (end_date - start_date)
    df["tender_days"] = (df["delivery_date"] - df["contract_period_start"]).dt.days

    # Convert tender_days to weeks
    df["tender_weeks"] = df["tender_days"] / 7

    df["weekly_average"] = df["original_value"] / df["tender_weeks"]


    # Filter based on the keyword in 'description_eng' column
    filtered_df = df[df["description_eng"].str.contains(keyword, case=False, na=False)]
    filtered_df = filtered_df[~filtered_df["comments_eng"].str.contains("omit|omitted", case=False, na=False)]
    filtered_df = filtered_df[filtered_df["comments_eng"]!="Due to a technical issue in the financial system for this reporting period, the total contract value reported may be inaccurate and will be updated as soon as possible."]
    filtered_df = filtered_df[filtered_df["tender_weeks"]>=1]
    # filtered_df = filtered_df[filtered_df["owner_org_en"]== org_keyword]
    return filtered_df, filtered_df.weekly_average.mean()

check, amount = process_tenders(df, "information technology")

amount

check.description_eng.iloc[0]

check.original_value.min()

check.columns

check[check["contract_value"]==0]

check[check["contract_value"]==0].comments_eng.iloc[1]

check.owner_org_en.value_counts()

