pipeline {
  agent any
    // PLaceholder text in place for kubernetes and docker variables. 
  tools {
    nodejs "node"
  }

  triggers {
    pollSCM('* * * * *') // Check for new commits every minute
  }

  environment {
    DOCKER_IMAGE_BACKEND = "mohamedto17/backend"
    DOCKER_IMAGE_FRONTEND = "mohamedto17/frontend"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install Dependencies') {
      parallel {
        stage('Backend') {
          steps {
            dir('apps/backend') {
              bat 'npm install'
            }
          }
        }
        stage('Frontend') {
          steps {
            dir('apps/frontend') {
              bat 'npm install'
              bat 'npm install chart.js'
            }
          }
        }
      }
    }

    stage('Lint') {
      parallel {
        stage('Lint Backend') {
          steps {
            dir('apps/backend') {
              bat 'npm run lint || exit /b 0'
            }
          }
        }
        stage('Lint Frontend') {
          steps {
            dir('apps/frontend') {
              bat 'npm run lint || exit /b 0'
            }
          }
        }
      }
    }

    stage('Run Tests') {
      parallel {
        stage('Backend Tests') {
          steps {
            dir('apps/backend') {
              bat 'npm test || exit /b 0'
            }
          }
        }
        stage('Frontend Tests') {
          steps {
            dir('apps/frontend') {
              bat 'npm test || exit /b 0'
            }
          }
        }
      }
    }

    stage('Build Docker Images') {
      steps {
        bat 'docker build -t %DOCKER_IMAGE_FRONTEND%:latest -f cicd/team_204/Dockerfile.frontend .'
        bat 'docker build -t %DOCKER_IMAGE_BACKEND%:latest -f cicd/team_204/Dockerfile.backend .'
      }
    }

    stage('Pubat Docker Images') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
          bat '''
            echo %DOCKER_PASS% | docker login -u %DOCKER_USER% --password-stdin
            docker push %DOCKER_IMAGE_BACKEND%:latest
            docker push %DOCKER_IMAGE_FRONTEND%:latest
          '''
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        bat '''
          kubectl apply -f cicd/team_204/k8s/backend-deployment.yaml
          kubectl apply -f cicd/team_204/k8s/backend-service.yaml
          kubectl apply -f cicd/team_204/k8s/frontend-deployment.yaml
          kubectl apply -f cicd/team_204/k8s/frontend-service.yaml
          kubectl apply -f cicd/team_204/k8s/ingress.yaml
        '''
      }
    }
  }
}
